openapi: 3.0.3
info:
 title: Library API
 version: 1.0.0
 description: STD22092
servers:
 - url: https://library.com


paths:
 /books:
   get:
     summary: Get all books
     description: Retrieve a list of all books.
     parameters:
       - $ref: '#/components/parameters/queryPagination'
       - $ref: '#/components/parameters/pageSize'
     responses:
       200:
         description: The list of books
         content:
           application/json:
             schema:
               type: array
               items:
                $ref: '#/components/schemas/Book'
       400:
        $ref: '#/components/responses/BadRequest'
       403:
        $ref: '#/components/responses/Forbidden'
       500:
        $ref: '#/components/responses/InternalServerError'

   put:
     summary: Create or update a list of books
     requestBody:
       content:
         application/json:
           schema:
             type: array
             items:
               $ref: '#/components/schemas/CrupdateBook'
     responses:
       200:
         description: The list of created or updated books
         content:
           application/json:
             schema:
               type: array
               items:
                $ref: '#/components/schemas/Book'
       400:
        $ref: '#/components/responses/BadRequest'
       403:
        $ref: '#/components/responses/Forbidden'
       500:
        $ref: '#/components/responses/InternalServerError'
         
components:
  parameters:
    pageSize:
      name: pageSize
      in: query
      description: The number of items per page 
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 50

    queryPagination:
      name: page
      in: query
      description: The page number for pagination 
      schema:
        type: integer
        default: 1

  responses:
    InternalServerError:
      description: Erreur interne du serveur
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
              body:
                type: object
                additionalProperties: true
                properties:
                  error:
                    type: string

    Forbidden:
      description: Accès interdit
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
              body:
                type: object
                additionalProperties: true
                properties:
                  error:
                    type: string

    BadRequest:
      description: Mauvaise requête
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
              body:
                type: object
                additionalProperties: true
                properties:
                  error:
                    type: string


  
  schemas:
    Author:
      type: object
      properties:
        bookName:
          type: string
        author:
          type: string
        pageNumbers:
          type: integer
        topic:
          type: string
        releaseDate:
          type: string
          format: date
        idAuthor:
          type: string
      required:
        - bookName
        - author
        - pageNumbers
        - topic
        - releaseDate
        - idAuthor

    AuthorImport:
      type: object
      properties:
        bookName:
          type: string
        author:
          type: string
        pageNumbers:
          type: integer
        topic:
          type: string
        releaseDate:
          type: string
          format: date
        idAuthor:
          type: string
      required:
        - bookName
        - author
        - pageNumbers
        - topic
        - releaseDate
        - idAuthor

    BookImport:
      type: object
      properties:
        bookName:
          type: string
        author:
          type: string
        pageNumbers:
          type: integer
        topic:
          type: string
        releaseDate:
          type: string
          format: date
        idAuthor:
          type: string
      required:
        - bookName
        - author
        - pageNumbers
        - topic
        - releaseDate
        - idAuthor

    Book:
     type: object
     properties:
       title:
         type: string
       author:
         type: string
       publication_year:
         type: integer
       Crupdatebook:
          type: string
     required:
       - title
       - author
       - publication_year
       - Crupdatebook
    CrupdateBook:
     type: object
     properties:
       title:
         type: string
