openapi: 3.0.3
info:
  title: Library API
  version: 1.0.0
  description: STD22092
servers:
  - url: https://library.com

paths:
  /books:
    get:
      summary: Get all books
      description: Retrieve a list of all books.
      responses:
        200:
          description: The list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

    put:
      summary: Create or update a list of books
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CrupdateBook'
      responses:
        200:
          description: The list of created or updated books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

  /authors:
    get:
      summary: Get all authors
      description: Retrieve a list of all authors.
      responses:
        200:
          description: The list of authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'

    put:
      summary: Create or update a list of authors
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Author'
      responses:
        200:
          description: The list of created or updated authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'

  /books/authors:
    put:
      summary: Attach Authors to Books
      description: Attach multiple Authors to multiple Books by specifying their IDs.
      operationId: attachAuthorsToBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Author'
      responses:
        200:
          description: The updated books with attached authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

  /books/{bookId}/authors/{authorId}:
    parameters:
      - in: path
        name: bookId
        description: ID of the book
        required: true
        schema:
          type: string
      - in: path
        name: authorId
        description: ID of the author
        required: true
        schema:
          type: string
    put:
      summary: Update the author of a book
      description: Update the author of a book by specifying their IDs.
      operationId: updateBookAuthor
      responses:
        200:
          description: The updated book with the new author
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
    x-secondOperation:
      put:
        summary: Update book authors in bulk
        description: Update the authors of multiple books by specifying their IDs.
        operationId: updateBooksAuthors
        requestBody:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UpdateBookAuthor'
        responses:
          200:
            description: The list of updated books with new authors
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Book'

components:
  schemas:
    CrupdateBook:
      type: object
      properties:
        id:
          type: string
        bookName:
          type: string
        pageNumbers:
          type: integer
        topic:
          type: string
          enum:
            - ROMANCE
            - COMEDY
            - OTHER
        releaseDate:
          type: string
          format: date

    Book:
      allOf:
        - $ref: '#/components/schemas/CrupdateBook'
        - type: object
          properties:
            author:
              $ref: '#/components/schemas/Author'

    Author:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        sex:
          type: string
          enum:
            - M
            - F

    UpdateBookAuthor:
      type: object
      properties:
        bookId:
          type: string
        authorId:
          type: string
