openapi: 3.0.3
info:
 title: Library API
 version: 1.0.0
 description: STD22092
servers:
 - url: https://library.com

paths:
 /books:
   get:
     summary: Get all books
     description: Retrieve a list of all books.
     parameters:
       - $ref: '#/components/parameters/queryPagination'
       - $ref: '#/components/parameters/pageSize'
     responses:
       200:
         description: The list of books
         content:
           application/json:
             schema:
               type: array
               items:
                $ref: '#/components/schemas/Book'

   put:
     summary: Create or update a list of books
     requestBody:
       content:
         application/json:
           schema:
             type: array
             items:
               $ref: '#/components/schemas/CrupdateBook'
     responses:
       200:
         description: The list of created or updated books
         content:
           application/json:
             schema:
               type: array
               items:
                $ref: '#/components/schemas/Book'

 /authors:
   get:
     summary: Get all authors
     description: Retrieve a list of all authors.
     parameters:
       - $ref: '#/components/parameters/queryPagination'
       - $ref: '#/components/parameters/pageSize'
     responses:
       200:
         description: The list of authors
         content:
           application/json:
             schema:
               type: array
               items:
                $ref: '#/components/schemas/Author'
                
components:
 parameters:
   queryPagination:
     name: page
     in: query
     description: The page number for pagination 
     schema:
       type: integer
       default: 1
   pageSize:
     name: pageSize
     in: query
     description: The number of items per page 
     schema:
       type: integer
       default: 50

 schemas:
   Book:
     type: object
     properties:
       title:
         type: string
       author:
         type: string
       publication_year:
         type: integer
     required:
       - title
       - author
       - publication_year

   CrupdateBook:
     type: object
     properties:
       title:
         type: string
       author:
         type: string
       publication_year:
         type: integer
     required:
       - title
       - author
       - publication_year

   Author:
     type: object
     properties:
       name:
         type: string
       nationality:
         type: string
     required:
       - name
       - nationality
